token:
  expiration_time: 86400000
  secret: '{cipher}AQBhtAim3afTbO+i8NfC+xvI3Qh8Xkp7lECgU3TaIhu78RUmWAdxny5MztTFzftmEiRCTzuZ5e3QZnaAtUHZw896HBwuurLg2jEkzKEqHCWM0bk5qSZOtNtPrpnryQYa4NN+BayJ6wPyowLdM8DeGqarGCxmXM0B5YZa+WVlHX2IKIY01jWKdONsLgWH/CLGQHisv/BZkvPqPfIZA7jgCHSJh7PLs0/wtckCd/7DIzha6wiU+KE+3ohG7ATgvciGiJU9O4i6d+tZiJRgLA0oz5187pcuKnCr19SCk6UrZc7/W2TpYgZ7mKyR7KcCe5S0MgF2IJz1zNixbuxXqC/Hu4Oqs+1MohmCSgEYL7fOAk8eTEhS73w2Ls+cOx3FGE0wD2dyGBJ0YWEcMpZXQsY7NFtU'

gateway:
  ip: 172.30.1.5
